[versions]
agp = "8.13.2"
glide = "5.0.5"
gson = "2.13.2"
kotlin = "2.3.0"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleLivedataKtx = "2.9.3"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2024.09.00"
appcompat = "1.7.1"
location = "6.4.3"
loggingInterceptor = "4.12.0"
lottie = "6.6.10"
material = "1.12.0"
animationCore = "1.9.0"
kotlinStdlib = "2.3.0"
kotlinxCoroutines = "1.7.3"
lifecycleService = "2.9.3"
mmkv = "1.3.9"
nanohttpd = "2.3.1"
opencv = "4.5.3.0"
roomPaging = "2.8.4"
search = "9.4.0"
securityCrypto = "1.1.0-alpha06"
okhttp = "4.9.0"
okhttpVersion = "4.12.0"
coreSplashscreen = "1.0.1"
roomCompiler = "2.8.4"
pagingCommon = "3.2.1"
roomKtx = "2.8.4"
roomRuntime = "2.8.4"
ktor = "3.1.3"
kotlinxSerializationJson = "1.6.3"
textRecognitionChinese = "16.0.1"
valiktor = "0.12.0"
composeMaterialCore = "1.5.2"
mustache = "0.9.10"
fastjson = "1.1.72.android"
bouncycastle = "1.78.1"
androidxNavigation = "2.8.9"
accompanistSystemuicontroller = "0.36.0"
anrwatchdog = "1.4.0"
blankjUtilcode = "1.31.1"
constraintlayout = "2.2.1"
navigationFragment = "2.8.9"
navigationUi = "2.8.9"
palette = "1.0.0"
shizuku = "13.1.5"
